- hosts: all
  tasks:

  - name: Install Prerequisites
    import_role:
      name: prer
  
  - include_tasks: "{{ ansible_os_family }}.yml" 

  - name: Install openjdk
    import_role:
      name: java